### ISSUE TITLE
`require` statements do not seem to work

### ISSUE THREAD

**Issue by chadcampbell** [hbenl/vscode-jasmine-test-adapter#3] opened 2018-06-03 20:35 UTC
I'm trying to test some code that I've written. However, this extension does not seem to work when I reference my code. For example, in my Jasmine file, I have the following:

```
const MyCode = require('../src/mine');

describe("Mine", function() {
    it("contains spec with an expectation", function() {
      expect(true).toBe(true);
    });
  });
```

This does not load the test in the 'TEST: TEST EXPLORER' pane. However, if I comment out the line beginning with `const MyCode ...`, and press the "refresh" button, the test does not appear. Yet, if I press the "play" button, it does work. I can successfully run the test *with* the `const MyCode ...` line from the command-line.

There seems to be two issues here: 

1. The refresh button in the 'TEST: TEST EXPLORER' does not seem to be working
2. Loading code via `require` does not seem to work

**Comment by hbenl** [comment] 2018-06-04 16:57
1. After clicking the refresh button you will only see the test files, the tests that are within them are only shown after running them - this is currently a known limitation of this extension (because initially I didn't know how to detect Jasmine tests without running them - now I know a way, so this will eventually be fixed)
2. I could not reproduce the problem with `require` (tested on Windows 10), may be you could publish a little test repository for reproducing this issue

**Comment by hbenl** [comment] 2018-07-06 19:30
The extension now forwards the jasmine console output to a VS Code output channel (this feature isn't documented yet): Have a look at the Output panel at the bottom of VS Code. After trying to load the tests, the dropdown should offer a channel "Jasmine Tests", which may help understanding why `require` doesn't work.

**Comment by hbenl** [comment] 2018-07-12 17:51
I've just published a new version that contains options for diagnostic logging (described in the [Troubleshooting](https://github.com/hbenl/vscode-jasmine-test-adapter#troubleshooting) section), please try again with that version and attach the logs.

**Comment by hbenl** [comment] 2018-08-03 20:07
No feedback > closing

**Closed by hbenl** 2018-08-03 20:07 UTC
Labels: bug, works for me
